### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fkromer** [anonymouse64/influxdb-snap#1]
Hi @anonymouse64, could you put a license into the repo and onto the [snap page](https://snapcraft.io/influxdb-ijohnson) pls?

**Comment by anonymouse64** [comment]
I added a license to the snapcraft.yaml, so when the snap is done building on LP it should show up on the snap page. Feel free to re-open if it doesn't show up and I forget to check in on it

**Comment by fkromer** [comment]
@anonymouse64 Great! Thx for MIT!
